---
title: "StudentData"
format: html
---

# Packages
```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
```

# Data 

```{r}
d <- read.csv("d.csv")

d <- d |>
  mutate(perc_1assessment = domain_1assessment/26,
         perc_2assessment = domain_2assessment/27,
         perc_3assessment = domain_3assessment/27,
         perc_4assessment = domain_4assessment/27,
         perc_5assessment = domain_5assessment/26)

d_long <- d |>
  pivot_longer(
    cols = starts_with(c("domain", "perc")),
    names_to = c(".value", "d"),
    names_sep = "_" # Or use names_pattern if there is no separator
  )

d_long <- d_long |>
  group_by(name) |>
  mutate(d = seq(1, 5, 1)) |>
  rename(score = domain,
         domain = d) |>
  ungroup()
```

# Visualizations

```{r}
wcavg <- d_long |>
  summarise(d1_score_mean = mean(score[d == 1], na.rm = TRUE),
            d2_score_mean = mean(score[d == 2], na.rm = TRUE),
            d3_score_mean = mean(score[d == 3], na.rm = TRUE),
            d4_score_mean = mean(score[d == 4], na.rm = TRUE),
            d5_score_mean = mean(score[d == 5], na.rm = TRUE)) |>
  as.matrix()

wcavg_perc <- d_long |>
  summarise(d1_perc_mean = mean(perc[d == 1], na.rm = TRUE),
            d2_perc_mean = mean(perc[d == 2], na.rm = TRUE),
            d3_perc_mean = mean(perc[d == 3], na.rm = TRUE),
            d4_perc_mean = mean(perc[d == 4], na.rm = TRUE),
            d5_perc_mean = mean(perc[d == 5], na.rm = TRUE)) |>
  as.matrix()

avgs <- data.frame(
  domain = seq(1, 5, 1),
  avg_score = wcavg[1,],
  avg_perc = wcavg_perc[1,]
)

avgs |>
  ggplot(aes(x = domain, y = avg_score)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(x = "Domain", y = "Average Score")

avgs |>
  ggplot(aes(x = domain, y = avg_perc)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(x = "Domain", y = "Average Percentage")
```


```{r}
p1 <- d_long |>
  filter(reading_group_eval == "red") |>
  ggplot(aes(x = d,
             y = perc,
             group = name, 
             color = name)) +
  geom_point() +
  geom_line() +
  # Use viridis for high-contrast, colorblind-friendly palettes
  scale_color_viridis_d(option = "turbo") + 
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "Domain", y = "Percentage")

p2 <- d_long |>
  filter(reading_group_eval == "orange") |>
  ggplot(aes(x = d,
             y = perc,
             group = name, 
             color = name)) +
  geom_point() +
  geom_line() +
  # Use viridis for high-contrast, colorblind-friendly palettes
  scale_color_viridis_d(option = "turbo") + 
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "Domain", y = "Percentage")

p3 <- d_long |>
  filter(reading_group_eval == "green") |>
  ggplot(aes(x = d,
             y = perc,
             group = name, 
             color = name)) +
  geom_point() +
  geom_line() +
  # Use viridis for high-contrast, colorblind-friendly palettes
  scale_color_viridis_d(option = "turbo") + 
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "Domain", y = "Percentage")

p4 <- d_long |>
  filter(reading_group_eval == "blue") |>
  ggplot(aes(x = d,
             y = perc,
             group = name, 
             color = name)) +
  geom_point() +
  geom_line() +
  # Use viridis for high-contrast, colorblind-friendly palettes
  scale_color_viridis_d(option = "turbo") + 
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "Domain", y = "Percentage")

grid.arrange(p1, p2, p3, p4, nrow = 2)
```






